In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/refs/heads/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [3]:
#!wget $data

In [4]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [5]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

# Data Preparation

In [7]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [8]:
# We can see that TotalCharges is a str but it should be an int. So we will convert it.

In [9]:
pd.to_numeric(df.TotalCharges, errors='coerce')
#In pd.to_numeric(), coerce means:
#If a value cannot be converted to a number, replace it with NaN instead of throwing an error.

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64

In [10]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')

In [11]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [12]:
df.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='str')

In [13]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges        float64
churn                   str
dtype: object

In [14]:
categorical_columns = list(df.dtypes[df.dtypes == 'str'].index)

In [15]:
for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [16]:
df.head().T

,0,1,2,3,4
customerid,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu
gender,female,male,male,male,female
seniorcitizen,0,0,0,0,0
partner,yes,no,no,no,no
dependents,no,no,no,no,no
tenure,1,34,2,45,2
phoneservice,no,yes,yes,no,yes
multiplelines,no_phone_service,no,no,no_phone_service,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic
onlinesecurity,no,yes,yes,yes,no
onlinebackup,yes,no,yes,no,no
deviceprotection,no,yes,no,yes,no
techsupport,no,no,no,yes,no
streamingtv,no,no,no,no,no
streamingmovies,no,no,no,no,no
contract,month-to-month,one_year,month-to-month,one_year,month-to-month
paperlessbilling,yes,no,yes,no,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,no,no,yes,no,yes

In [17]:
df.churn

0        no
1        no
2       yes
3        no
4       yes
       ...
7038     no
7039     no
7040     no
7041    yes
7042     no
Name: churn, Length: 7043, dtype: str

In [18]:
df.churn = (df.churn == 'yes').astype(int)

In [19]:
df.churn.head()

0    0
1    0
2    1
3    0
4    1
Name: churn, dtype: int64

In [20]:
df.isnull().sum()

customerid           0
gender               0
seniorcitizen        0
partner              0
dependents           0
tenure               0
phoneservice         0
multiplelines        0
internetservice      0
onlinesecurity       0
onlinebackup         0
deviceprotection     0
techsupport          0
streamingtv          0
streamingmovies      0
contract             0
paperlessbilling     0
paymentmethod        0
monthlycharges       0
totalcharges        11
churn                0
dtype: int64

In [21]:
df.totalcharges = df.totalcharges.fillna(0)

# Setting Up Validation Framework

* ### Splitting this dataset into training/validation/test using Scikit-Learn

In [22]:
from sklearn.model_selection import train_test_split

#### train_test_split is a function that breaks the dataset into two parts, training and test. But we will split it more for validation.

In [23]:
df_full_train, df_test = train_test_split(df, test_size= 0.2, random_state= 1)

In [24]:
len(df_full_train), len(df_test)

(5634, 1409)

#### Now our data is split into 80:20, but from that 80 percent we need to make it 60:20. 20% of 80% is 25%.

In [25]:
df_train, df_val = train_test_split(df_full_train, test_size= 0.25, random_state= 1)

In [26]:
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [27]:
df_train.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
3897,8015-ihcgw,female,0,yes,yes,72,yes,yes,fiber_optic,yes,...,yes,yes,yes,yes,two_year,yes,electronic_check,115.50,8425.15,0
1980,1960-uycnn,male,0,no,no,10,yes,yes,fiber_optic,no,...,yes,no,no,yes,month-to-month,yes,electronic_check,95.25,1021.55,0
6302,9250-wypll,female,0,no,no,5,yes,yes,fiber_optic,no,...,no,no,no,no,month-to-month,no,electronic_check,75.55,413.65,1
727,6786-obwqr,female,0,yes,yes,5,yes,no,fiber_optic,no,...,no,no,yes,no,month-to-month,yes,electronic_check,80.85,356.10,0
5104,1328-euzhc,female,0,yes,no,18,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,20.10,370.50,0

In [28]:
df_full_train = df_full_train.reset_index(drop= True)
df_train = df_train.reset_index(drop= True)
df_val = df_val.reset_index(drop= True)
df_test = df_test.reset_index(drop= True)

In [29]:
df_train.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,8015-ihcgw,female,0,yes,yes,72,yes,yes,fiber_optic,yes,...,yes,yes,yes,yes,two_year,yes,electronic_check,115.50,8425.15,0
1,1960-uycnn,male,0,no,no,10,yes,yes,fiber_optic,no,...,yes,no,no,yes,month-to-month,yes,electronic_check,95.25,1021.55,0
2,9250-wypll,female,0,no,no,5,yes,yes,fiber_optic,no,...,no,no,no,no,month-to-month,no,electronic_check,75.55,413.65,1
3,6786-obwqr,female,0,yes,yes,5,yes,no,fiber_optic,no,...,no,no,yes,no,month-to-month,yes,electronic_check,80.85,356.10,0
4,1328-euzhc,female,0,yes,no,18,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,20.10,370.50,0

In [30]:
y_full_train = df_full_train['churn'].values
y_train = df_train['churn'].values
y_val = df_val['churn'].values
y_test = df_test['churn'].values

In [31]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

In [32]:
df_train.head().T

,0,1,2,3,4
customerid,8015-ihcgw,1960-uycnn,9250-wypll,6786-obwqr,1328-euzhc
gender,female,male,female,female,female
seniorcitizen,0,0,0,0,0
partner,yes,no,no,yes,yes
dependents,yes,no,no,yes,no
tenure,72,10,5,5,18
phoneservice,yes,yes,yes,yes,yes
multiplelines,yes,yes,yes,no,no
internetservice,fiber_optic,fiber_optic,fiber_optic,fiber_optic,no
onlinesecurity,yes,no,no,no,no_internet_service
onlinebackup,yes,yes,no,no,no_internet_service
deviceprotection,yes,yes,no,no,no_internet_service
techsupport,yes,no,no,no,no_internet_service
streamingtv,yes,no,no,yes,no_internet_service
streamingmovies,yes,yes,no,no,no_internet_service
contract,two_year,month-to-month,month-to-month,month-to-month,two_year
paperlessbilling,yes,yes,no,yes,no
paymentmethod,electronic_check,electronic_check,electronic_check,electronic_check,mailed_check
monthlycharges,115.5,95.25,75.55,80.85,20.1
totalcharges,8425.15,1021.55,413.65,356.1,370.5

# Exploratory Data Analysis

* #### Check missing values.
* #### Look at target value(churn).
* #### Look at numerical and categorical variables.

In [33]:
df.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [34]:
np.unique(y_full_train, return_counts= True)
# Basically 0 = 73%, 1 = 27%

(array([0, 1]), array([4113, 1521]))

In [35]:
global_churn_rate = y_full_train.mean()
round(global_churn_rate, 2)

np.float64(0.27)

In [36]:
df_full_train.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges        float64
churn                 int64
dtype: object

In [37]:
numerical = ['tenure', 'monthlycharges', 'totalcharges']

In [38]:
df_full_train.dtypes.index

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='str')

In [39]:
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
          'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod']

In [40]:
categorical

['gender',
 'seniorcitizen',
 'partner',
 'dependents',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod']

In [41]:
df[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

# Feature importance: Churn Rate and Risk Ratio

#### Feature importance analysis(part of EDA) - Identifying which features affect our target variable.

* #### Churn rate
* #### Risk ratio
* #### Mutual information

#### Churn rate and Risk ratio

#### Refer notebook for notes on these concepts.

In [42]:
global_churn_rate = df_full_train.churn.mean()
global_churn_rate

np.float64(0.26996805111821087)

In [43]:
churn_female = df_full_train[df_full_train['gender'] == 'female'].churn.mean()
churn_female

np.float64(0.27682403433476394)

In [44]:
churn_male = df_full_train[df_full_train['gender'] == 'male'].churn.mean()
churn_male

np.float64(0.2632135306553911)

In [45]:
churn_partner = df_full_train[df_full_train['partner'] == 'yes'].churn.mean()
churn_partner

np.float64(0.20503330866025166)

In [46]:
churn_no_partner = df_full_train[df_full_train['partner'] == 'no'].churn.mean()
churn_no_partner

np.float64(0.3298090040927694)

In [47]:
df_full_train.groupby('gender').churn.mean()

gender
female    0.276824
male      0.263214
Name: churn, dtype: float64

In [48]:
df_full_train.groupby('gender').churn.agg(['mean', 'count'])
# This creates a dataframe for us that divides the data into caregories, and apply functions on it.

            mean  count
gender
female  0.276824   2796
male    0.263214   2838

In [49]:
df_group = df_full_train.groupby('gender').churn.agg(['mean', 'count'])
df_group['Diff'] = global_churn_rate - df_group['mean']
df_group['Risk'] = df_group['mean'] / global_churn_rate

df_group

            mean  count      Diff      Risk
gender
female  0.276824   2796 -0.006856  1.025396
male    0.263214   2838  0.006755  0.974980

#### Let's do this for all categorical variables.

In [50]:
from IPython.display import display

In [51]:
for c in categorical:
    df_group = df_full_train.groupby(c).churn.agg(['mean', 'count'])
    df_group['Diff'] = global_churn_rate - df_group['mean']
    df_group['Risk'] = df_group['mean'] / global_churn_rate
    print(c)
    display(df_group)
    print()
    print()

gender

            mean  count      Diff      Risk
gender
female  0.276824   2796 -0.006856  1.025396
male    0.263214   2838  0.006755  0.974980

seniorcitizen

                   mean  count      Diff      Risk
seniorcitizen
0              0.242270   4722  0.027698  0.897403
1              0.413377    912 -0.143409  1.531208

partner

             mean  count      Diff      Risk
partner
no       0.329809   2932 -0.059841  1.221659
yes      0.205033   2702  0.064935  0.759472

dependents

                mean  count      Diff      Risk
dependents
no          0.313760   3968 -0.043792  1.162212
yes         0.165666   1666  0.104302  0.613651

phoneservice

                  mean  count      Diff      Risk
phoneservice
no            0.241316    547  0.028652  0.893870
yes           0.273049   5087 -0.003081  1.011412

multiplelines

                      mean  count      Diff      Risk
multiplelines
no                0.257407   2700  0.012561  0.953474
no_phone_service  0.241316    547  0.028652  0.893870
yes               0.290742   2387 -0.020773  1.076948

internetservice

                     mean  count      Diff      Risk
internetservice
dsl              0.192347   1934  0.077621  0.712482
fiber_optic      0.425171   2479 -0.155203  1.574895
no               0.077805   1221  0.192163  0.288201

onlinesecurity

                         mean  count      Diff      Risk
onlinesecurity
no                   0.420921   2801 -0.150953  1.559152
no_internet_service  0.077805   1221  0.192163  0.288201
yes                  0.153226   1612  0.116742  0.567570

onlinebackup

                         mean  count      Diff      Risk
onlinebackup
no                   0.404323   2498 -0.134355  1.497672
no_internet_service  0.077805   1221  0.192163  0.288201
yes                  0.217232   1915  0.052736  0.804660

deviceprotection

                         mean  count      Diff      Risk
deviceprotection
no                   0.395875   2473 -0.125907  1.466379
no_internet_service  0.077805   1221  0.192163  0.288201
yes                  0.230412   1940  0.039556  0.853480

techsupport

                         mean  count      Diff      Risk
techsupport
no                   0.418914   2781 -0.148946  1.551717
no_internet_service  0.077805   1221  0.192163  0.288201
yes                  0.159926   1632  0.110042  0.592390

streamingtv

                         mean  count      Diff      Risk
streamingtv
no                   0.342832   2246 -0.072864  1.269897
no_internet_service  0.077805   1221  0.192163  0.288201
yes                  0.302723   2167 -0.032755  1.121328

streamingmovies

                         mean  count      Diff      Risk
streamingmovies
no                   0.338906   2213 -0.068938  1.255358
no_internet_service  0.077805   1221  0.192163  0.288201
yes                  0.307273   2200 -0.037305  1.138182

contract

                    mean  count      Diff      Risk
contract
month-to-month  0.431701   3104 -0.161733  1.599082
one_year        0.120573   1186  0.149395  0.446621
two_year        0.028274   1344  0.241694  0.104730

paperlessbilling

                      mean  count      Diff      Risk
paperlessbilling
no                0.172071   2313  0.097897  0.637375
yes               0.338151   3321 -0.068183  1.252560

paymentmethod

                               mean  count      Diff      Risk
paymentmethod
bank_transfer_(automatic)  0.168171   1219  0.101797  0.622928
credit_card_(automatic)    0.164339   1217  0.105630  0.608733
electronic_check           0.455890   1893 -0.185922  1.688682
mailed_check               0.193870   1305  0.076098  0.718121

### Mutual Information

#### Go to this link for proper explanation. - https://www.youtube.com/watch?v=eJIp_mgVLwE&t=379s

In [53]:
from sklearn.metrics import mutual_info_score

In [54]:
mutual_info_score(df_full_train.churn, df_full_train.gender)

0.0001174846211139946

#### Similarly we can apply this function to all the categoical columns.

In [55]:
def mutual_info_churn_score(column):
    return mutual_info_score(column, df_full_train.churn)

In [57]:
mi = df_full_train[categorical].apply(mutual_info_churn_score)
mi.sort_values(ascending = False)

contract            0.098320
onlinesecurity      0.063085
techsupport         0.061032
internetservice     0.055868
onlinebackup        0.046923
deviceprotection    0.043453
paymentmethod       0.043210
streamingtv         0.031853
streamingmovies     0.031581
paperlessbilling    0.017589
dependents          0.012346
partner             0.009968
seniorcitizen       0.009410
multiplelines       0.000857
phoneservice        0.000229
gender              0.000117
dtype: float64

#### Now we can see the mutual information of each categorical variable with churn.